/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pombensin.ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Nurcholis Rio
 */
public class DashboardAdmin extends javax.swing.JFrame {
    
    CardLayout cl;

    /**
     * Creates new form Dashboard
     */
    public DashboardAdmin() {
        initComponents();
        cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel,"panelHarian");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelHarian2 = new pombensin.ui.PanelHarian();
        panelDaftarBensin2 = new pombensin.ui.PanelDaftarBensin();
        panelDaftarPelanggan1 = new pombensin.ui.PanelDaftarPelanggan();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnTotal = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuPelanggan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuBensin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(panelHarian2, "tabelHarian");
        mainPanel.add(panelDaftarBensin2, "tabelBensin");
        mainPanel.add(panelDaftarPelanggan1, "tabelPelanggan");

        jMenu4.setText("Beranda");

        jMenuItem2.setText("Login Pelanggan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem1.setText("Keluar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Total Harian");

        mnTotal.setText("Harian Total");
        mnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTotalActionPerformed(evt);
            }
        });
        jMenu2.add(mnTotal);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Daftar Pelanggan");

        menuPelanggan.setText("Tabel Pelanggan");
        menuPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPelangganActionPerformed(evt);
            }
        });
        jMenu1.add(menuPelanggan);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Daftar Bensin");

        menuBensin.setText("TabelBensin");
        menuBensin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBensinActionPerformed(evt);
            }
        });
        jMenu3.add(menuBensin);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTotalActionPerformed
        cl.show(mainPanel,"tabelHarian");
    }//GEN-LAST:event_mnTotalActionPerformed

    private void menuPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPelangganActionPerformed
        cl.show(mainPanel,"tabelPelanggan");
    }//GEN-LAST:event_menuPelangganActionPerformed

    private void menuBensinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBensinActionPerformed
        cl.show(mainPanel,"tabelBensin");
    }//GEN-LAST:event_menuBensinActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int Action = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ke Login Pelanggan  ? ","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(Action==0){new LoginPelanggan().show();
        this.dispose();}
        else{}
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem menuBensin;
    private javax.swing.JMenuItem menuPelanggan;
    private javax.swing.JMenuItem mnTotal;
    private pombensin.ui.PanelDaftarBensin panelDaftarBensin2;
    private pombensin.ui.PanelDaftarPelanggan panelDaftarPelanggan1;
    private pombensin.ui.PanelHarian panelHarian2;
    // End of variables declaration//GEN-END:variables
}
