/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pombensin.ui;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pombensin.config.Koneksi;
import pombensin.model.DBPelanggan;


/**
 *
 * @author Nurcholis Rio
 */
public class LoginAdmin extends javax.swing.JFrame {
    private DBPelanggan pelanggan;
    private Koneksi conn;
    public ResultSet rs;
    /**
     * Creates new form LoginAdmin
     */
    public LoginAdmin() {
        try {
            pelanggan = new DBPelanggan();
            conn = new Koneksi();
            this.setLocationRelativeTo(null);
            initComponents();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoginAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LoginAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void masukAdmin()
    {
        try{
            String nama = masukUser.getText();
            String input = new String(masukPassword.getPassword());
            String sql = "Select * From admin Where nama = '"+nama+"' And password ='"+input+"'";
            conn.query(sql);
            rs=conn.rs;
            int baris=0;
            while(rs.next())
            {
                baris=rs.getRow();
            }
            if(baris==1)
            {
               new DashboardAdmin().show();
               this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "User dan Password Salah silahkan Coba lagi kembali");
                masukUser.setText("");
                masukPassword.setText("");
            }
            
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlePelanggan = new javax.swing.JLabel();
        TitleNama = new javax.swing.JLabel();
        TitlePassword = new javax.swing.JLabel();
        masukUser = new javax.swing.JTextField();
        masukPassword = new javax.swing.JPasswordField();
        AksiMasuk = new javax.swing.JButton();
        AksiKeluar = new javax.swing.JButton();
        AksiPelanggan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitlePelanggan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TitlePelanggan.setText("Login Admin Pom");

        TitleNama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TitleNama.setText("Username");

        TitlePassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TitlePassword.setText("Password");

        masukUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukUserActionPerformed(evt);
            }
        });

        AksiMasuk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AksiMasuk.setText("Masuk");
        AksiMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AksiMasukActionPerformed(evt);
            }
        });

        AksiKeluar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AksiKeluar.setText("Keluar");

        AksiPelanggan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AksiPelanggan.setText("Pelanggan");
        AksiPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AksiPelangganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(TitlePelanggan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleNama)
                    .addComponent(TitlePassword)
                    .addComponent(AksiPelanggan))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AksiMasuk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AksiKeluar))
                    .addComponent(masukPassword)
                    .addComponent(masukUser))
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(TitlePelanggan)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleNama)
                    .addComponent(masukUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitlePassword)
                    .addComponent(masukPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AksiMasuk)
                    .addComponent(AksiKeluar)
                    .addComponent(AksiPelanggan))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masukUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukUserActionPerformed
        System.exit(0);
    }//GEN-LAST:event_masukUserActionPerformed

    private void AksiMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AksiMasukActionPerformed
        masukAdmin();
    }//GEN-LAST:event_AksiMasukActionPerformed

    private void AksiPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AksiPelangganActionPerformed
        new LoginPelanggan().show();
        this.dispose();
    }//GEN-LAST:event_AksiPelangganActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AksiKeluar;
    private javax.swing.JButton AksiMasuk;
    private javax.swing.JButton AksiPelanggan;
    private javax.swing.JLabel TitleNama;
    private javax.swing.JLabel TitlePassword;
    private javax.swing.JLabel TitlePelanggan;
    private javax.swing.JPasswordField masukPassword;
    private javax.swing.JTextField masukUser;
    // End of variables declaration//GEN-END:variables
}
