/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pombensin.ui;

import pombensin.model.DBJenisBensin;
import pombensin.model.JenisBensin;

/**
 *
 * @author Nurcholis Rio
 */
public class PanelDaftarBensin extends javax.swing.JPanel {
    private DBJenisBensin jenisbensin;
    private JenisBensin bensinedit;
    /**
     * Creates new form PanelDaftarBensin
     */
    public PanelDaftarBensin() {
        jenisbensin = new DBJenisBensin();
        bensinedit = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBensin = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        saveBensin = new javax.swing.JButton();
        resetBensin = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Tabel Daftar Bensin");

        tblBensin.setModel(new ATMDaftarBensin());
        tblBensin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBensinMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBensin);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama Bensin");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Harga Bensin");

        txtNama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNama.setToolTipText("");

        txtHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHarga.setToolTipText("");

        saveBensin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveBensin.setText("Simpan");
        saveBensin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBensinActionPerformed(evt);
            }
        });

        resetBensin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resetBensin.setText("Reset");
        resetBensin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBensinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(resetBensin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(saveBensin))
                                    .addComponent(txtHarga))))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(363, 363, 363))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBensin)
                    .addComponent(resetBensin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBensinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBensinActionPerformed
        if(bensinedit == null)
        {
            jenisbensin.addBensin(
                txtNama.getText(),
                Integer.parseInt(txtHarga.getText()));
        }
        else
        {
            bensinedit.jenisBensin = txtNama.getText();
            bensinedit.harga = Integer.parseInt(txtHarga.getText());
            jenisbensin.editBensin(bensinedit);
            bensinedit=null;
        }
        txtNama.setText("");
        txtHarga.setText("");
        tblBensin.setModel(new ATMDaftarBensin());
    }//GEN-LAST:event_saveBensinActionPerformed

    private void resetBensinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBensinActionPerformed
        txtNama.setText("");
        txtHarga.setText("");
    }//GEN-LAST:event_resetBensinActionPerformed

    private void tblBensinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBensinMouseClicked
        ATMDaftarBensin tbBensin = ((ATMDaftarBensin)tblBensin.getModel());
        bensinedit = tbBensin.data.get(tblBensin.getSelectedRow());
        txtNama.setText(bensinedit.jenisBensin);
        txtHarga.setText(Integer.toString(bensinedit.harga));
    }//GEN-LAST:event_tblBensinMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resetBensin;
    private javax.swing.JButton saveBensin;
    private javax.swing.JTable tblBensin;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
