/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pombensin.ui;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pombensin.config.Koneksi;
import pombensin.ui.Dashboard;
import pombensin.model.DBJenisBensin;
import pombensin.model.JenisBensin;
import pombensin.model.DBKalkulator;
import pombensin.model.DBStrukPembelian;
import pombensin.model.StrukPembelian;

/**
 *
 * @author Nurcholis Rio
 */
public class PanelBensin extends javax.swing.JPanel {
    
    private DBJenisBensin JenisBensin;
    private DBKalkulator KalkulatorBensin;
    private DBStrukPembelian StrukPembelian;
    private Koneksi conn;
    public  ResultSet rs;
    private StrukPembelian pembelianedit;
    
    /**
     * Creates new form KalkulatorBensin
     */
    public PanelBensin() {
        try {
            JenisBensin = new DBJenisBensin();
            KalkulatorBensin = new DBKalkulator();
            StrukPembelian = new DBStrukPembelian();
            conn = new Koneksi();
            initComponents();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelBensin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PanelBensin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private ComboBoxModel getComboBensin(){
        ArrayList<JenisBensin> jenisBensins = JenisBensin.getAllBensincmb();
        return new DefaultComboBoxModel(jenisBensins.toArray());
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtJudul = new javax.swing.JLabel();
        jenisbensin = new javax.swing.JLabel();
        cmbBensin = new javax.swing.JComboBox<>();
        hargaperliter = new javax.swing.JLabel();
        txtLiter = new javax.swing.JLabel();
        rpBelibensin = new javax.swing.JLabel();
        txtBeliBensin = new javax.swing.JTextField();
        Jumlahbensindibeli = new javax.swing.JLabel();
        txtjmlBensin = new javax.swing.JLabel();
        namapelanggan = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        txtPelanggan = new javax.swing.JTextField();
        harapdipilihkembali = new javax.swing.JLabel();
        btntampiltakaran = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTakaran = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtStruk = new javax.swing.JTextArea();
        cetakstruk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();

        txtJudul.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtJudul.setText("Selamat Datang di Pom Bensin");

        jenisbensin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jenisbensin.setText("Jenis Bensin");

        cmbBensin.setModel(getComboBensin());
        cmbBensin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBensinActionPerformed(evt);
            }
        });

        hargaperliter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hargaperliter.setText("Harga per Liter ");

        txtLiter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        rpBelibensin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rpBelibensin.setText("Beli Bensin (Rp)");

        txtBeliBensin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Jumlahbensindibeli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jumlahbensindibeli.setText("Jumlah Liter");

        txtjmlBensin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtjmlBensin.setText(" ");

        namapelanggan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namapelanggan.setText("Nama Pelanggan");

        btnProses.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnProses.setText("Proses Rupiah");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        harapdipilihkembali.setText("*Harap dipilih kembali");

        btntampiltakaran.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btntampiltakaran.setText("Tampil Takaran");
        btntampiltakaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntampiltakaranActionPerformed(evt);
            }
        });

        txtTakaran.setColumns(20);
        txtTakaran.setRows(5);
        jScrollPane1.setViewportView(txtTakaran);

        txtStruk.setColumns(20);
        txtStruk.setRows(5);
        jScrollPane2.setViewportView(txtStruk);

        cetakstruk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cetakstruk.setText("Tampil Struk");
        cetakstruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakstrukActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tampilan Struk");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tampilan Takaran");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Form Pom Bensin");

        Reset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Keluar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(170, 170, 170)
                        .addComponent(txtJudul))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(namapelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Jumlahbensindibeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jenisbensin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hargaperliter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rpBelibensin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtBeliBensin, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(cmbBensin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtPelanggan)
                                            .addComponent(txtLiter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtjmlBensin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(harapdipilihkembali)
                                                .addGap(3, 3, 3))
                                            .addComponent(btntampiltakaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnProses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cetakstruk)
                                        .addGap(53, 53, 53)
                                        .addComponent(Reset)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Keluar))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(133, 133, 133)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(namapelanggan)
                                    .addComponent(txtPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jenisbensin)
                                    .addComponent(cmbBensin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(harapdipilihkembali))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hargaperliter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtLiter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rpBelibensin)
                                    .addComponent(txtBeliBensin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnProses))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btntampiltakaran)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtjmlBensin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(Jumlahbensindibeli, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtJudul)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cetakstruk)
                            .addComponent(Reset)
                            .addComponent(Keluar))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
         txtjmlBensin.setText(KalkulatorBensin.jumlahbensin(txtLiter.getText(), txtBeliBensin.getText()));
    }//GEN-LAST:event_btnProsesActionPerformed

    private void cmbBensinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBensinActionPerformed
        JenisBensin.cmbSelectBensin(cmbBensin, txtLiter);
    }//GEN-LAST:event_cmbBensinActionPerformed

    private void btntampiltakaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntampiltakaranActionPerformed
        KalkulatorBensin.TampilTakaran(txtjmlBensin, txtTakaran);
    }//GEN-LAST:event_btntampiltakaranActionPerformed

    private void cetakstrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakstrukActionPerformed
        JenisBensin.cmbSelectBensin(cmbBensin, txtLiter);
        String nama = txtPelanggan.getText();
        int liter = Integer.parseInt(txtLiter.getText());
        int totalbeli=Integer.parseInt(txtBeliBensin.getText());
        double totalliter = Double.parseDouble(txtjmlBensin.getText());
        StrukPembelian.printStruk(nama,(JenisBensin)cmbBensin.getSelectedItem(),liter,totalbeli,totalliter,txtStruk);
        StrukPembelian.addStruk(nama,((JenisBensin)cmbBensin.getSelectedItem()).idJenisbensin,liter,totalbeli,totalliter);
        int Action = JOptionPane.showConfirmDialog(null, "Apakah anda transaksi kembali ? ","Reset",JOptionPane.YES_NO_OPTION);
        if(Action==0){txtPelanggan.setText("");txtLiter.setText("");txtBeliBensin.setText("");txtjmlBensin.setText("");txtTakaran.setText("");txtStruk.setText("");}
        else{JOptionPane.showMessageDialog(null, "Terima Kasih" );}
    }//GEN-LAST:event_cetakstrukActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        txtPelanggan.setText("");txtLiter.setText("");txtBeliBensin.setText("");txtjmlBensin.setText("");txtTakaran.setText("");txtStruk.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_KeluarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jumlahbensindibeli;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Reset;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btntampiltakaran;
    private javax.swing.JButton cetakstruk;
    private javax.swing.JComboBox<String> cmbBensin;
    private javax.swing.JLabel harapdipilihkembali;
    private javax.swing.JLabel hargaperliter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jenisbensin;
    private javax.swing.JLabel namapelanggan;
    private javax.swing.JLabel rpBelibensin;
    private javax.swing.JTextField txtBeliBensin;
    private javax.swing.JLabel txtJudul;
    private javax.swing.JLabel txtLiter;
    private javax.swing.JTextField txtPelanggan;
    private javax.swing.JTextArea txtStruk;
    private javax.swing.JTextArea txtTakaran;
    private javax.swing.JLabel txtjmlBensin;
    // End of variables declaration//GEN-END:variables
}
